###### 1. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array. 
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]


In [1]:
A = [12.23, 13.32, 100, 36.32]

In [2]:
print(type(A))

<class 'list'>


In [3]:
import numpy as np

In [4]:
B = np.array(A)
print(B)

[ 12.23  13.32 100.    36.32]


In [5]:
print(type(B))

<class 'numpy.ndarray'>


###### 2.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.  
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [6]:
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

###### 3. Write a NumPy program to create a null vector of size 10 and update sixth value to 11. 
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [7]:
A = (np.zeros(10))

In [8]:
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
A[6]=11

In [10]:
print(A)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


###### 4. Write a NumPy program to create an array with values ranging from 12 to 38. 
Expected Output:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [11]:
A = np.arange(12,38)

In [12]:
print(A)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [13]:
A = range(12,28)
print(A)


for i in A:
    print(i,end=",")

range(12, 28)
12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,

###### 5. Write a NumPy program to reverse an array (first element becomes last). 
 
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [14]:
A = np.arange(12,38)

In [15]:
print(A)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [16]:
B=A[-1::-1]
print(B)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


###### 6. Write a NumPy program to convert an array to a float type.  
Sample output:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]

In [17]:
A = np.arange(1,10)
print(A)

[1 2 3 4 5 6 7 8 9]


In [18]:
B = np.asfarray(A)

In [19]:
print(B)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


###### 7. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]


In [80]:
x = np.ones((5,5))

In [81]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [82]:
x[1:-1,1:-1] = 0

In [23]:
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###### 8. Write a NumPy program to add a border (filled with 0's) around an existing array.  
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
...........
[ 0. 0. 0. 0. 0.]]


In [24]:
A = np.ones((3,3))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
A = np.pad(A,pad_width=1,mode='constant',constant_values=9)

In [26]:
A

array([[9., 9., 9., 9., 9.],
       [9., 1., 1., 1., 9.],
       [9., 1., 1., 1., 9.],
       [9., 1., 1., 1., 9.],
       [9., 9., 9., 9., 9.]])

###### 9. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.  
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]


In [27]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


###### 10. Write a NumPy program to convert a list and tuple into arrays. 
 List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]


In [28]:
A = list([1,2,3,4,5,6,7,8])
A

[1, 2, 3, 4, 5, 6, 7, 8]

In [29]:
B =  np.array(A).reshape(2,4)
B

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
C = np.asarray(A)
C

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
D =  ([1,2,3,4],[5,6,7,8])

In [32]:
np.asarray(D)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

###### 11. Write a NumPy program to append values to the end of an array.  
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


In [33]:
A = [10,20,30]

In [34]:
np.append(A,([[40,50,60],[70,80,90]]))

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

###### 12. Write a NumPy program to create an empty and a full array. 
 Expected Output:
[ 6.93270651e-310 1.59262180e-316 6.93270559e-310 6.93270665e-310]
[ 6.93270667e-310 6.93270671e-310 6.93270668e-310 6.93270483e-310]
[ 6.93270668e-310 6.93270671e-310 6.93270370e-310 6.93270488e-310]]
[[6 6 6]
[6 6 6]
[6 6 6]]

In [35]:
A = np.empty((3,4))

In [36]:
A

array([[8.70270693e-312, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.21480179e-046, 3.11035595e+179,
        9.13741749e+169],
       [5.85343966e+170, 1.00632631e-046, 1.46301596e+185,
        1.57211872e-076]])

In [37]:
B = np.full((3,3),6)
B

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

###### 13. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array. 
 Sample Array [0, 12, 45.21 ,34, 99.91]
Expected Output:
Values in Fahrenheit degrees:
[ 0. 12. 45.21 34. 99.91]
Values in Centigrade degrees:
[-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]



In [38]:
fvalues = [0, 12, 45.21, 34, 99.91]

In [39]:
f = np.array(fvalues)

In [40]:
print(5*f/9-5*32/9)

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


###### 14. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.  
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]


In [69]:
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])

In [71]:
print(x.real)

[1.]


In [72]:
print(y.real)

[0.70710678]


In [73]:
print(x.imag)

[0.]


In [74]:
print(y.imag)

[0.70710678]
